_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.8.20
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
max_iterations:
    value: null
num_envs:
    value: null
seed:
    value: null
task:
    value: h1
train_config:
    value: <legged_gym.envs.h1.h1_config.H1RoughCfgPPO object at 0x7f3321453130>
